local M = require("helper.utils")
local wk = M.safe_require("which-key")

if wk then
    wk.setup({
        preset = "modern",
        delay = 300,
        icons = {
            mappings = true,
            separator = "➜",
            group = "",
        },
        win = {
            border = "rounded",
            padding = { 1, 2 },
        },
        layout = {
            spacing = 4,
        },
    })

    wk.add({
        { "<A-h>", desc = "Window Left", icon = { icon = "󰁍", color = "blue" } },
        { "<A-j>", desc = "Window Down", icon = { icon = "󰁅", color = "blue" } },
        { "<A-k>", desc = "Window Up", icon = { icon = "󰁝", color = "blue" } },
        { "<A-l>", desc = "Window Right", icon = { icon = "󰁔", color = "blue" } },
        { "<M-a>", desc = "Select All Matches", icon = { icon = "󰗧", color = "purple" } },
        { "<M-n>", desc = "Start / Next Multi-cursor", icon = { icon = "󰗧", color = "purple" } },
        { "<M-p>", desc = "Previous Multi-cursor Match", icon = { icon = "󰗧", color = "purple" } },
        { "<M-x>", desc = "Skip Multi-cursor Match", icon = { icon = "󰗧", color = "purple" } },
        { "g<M-a>", desc = "Select All Matches (No Boundary)", icon = { icon = "󰗧", color = "purple" } },
        { "g<M-n>", desc = "Start Multi-cursor (No Boundary)", icon = { icon = "󰗧", color = "purple" } },
        { "<C-Down>", desc = "Decrease Window Height", icon = { icon = "󰁅", color = "cyan" } },
        { "<C-Left>", desc = "Decrease Window Width", icon = { icon = "󰁍", color = "cyan" } },
        { "<C-Right>", desc = "Increase Window Width", icon = { icon = "󰁔", color = "cyan" } },
        { "<C-Up>", desc = "Increase Window Height", icon = { icon = "󰁝", color = "cyan" } },
        { "<C-f>", desc = "Focus File Explorer", icon = { icon = "󰉋", color = "yellow" } },
        { "<C-n>", desc = "Reveal in File Explorer", icon = { icon = "󰉋", color = "yellow" } },
        { "<C-t>", desc = "Toggle File Explorer", icon = { icon = "󰉋", color = "yellow" } },
        { "<F5>", desc = "Debug Continue", icon = { icon = "", color = "green" } },
        { "<F10>", desc = "Debug Step Over", icon = { icon = "", color = "blue" } },
        { "<F11>", desc = "Debug Step Into", icon = { icon = "", color = "blue" } },
        { "<F12>", desc = "Debug Step Out", icon = { icon = "", color = "blue" } },
        { "<S-Tab>", desc = "Previous Buffer", icon = { icon = "󰁍", color = "blue" } },
        { "<Tab>", desc = "Next Buffer", icon = { icon = "󰁔", color = "blue" } },
        { "K", desc = "Hover Documentation", icon = { icon = "󰋖", color = "azure" } },
        { "N", desc = "Previous Search Centered", icon = { icon = "󰍉", color = "azure" } },
        { "S", desc = "Flash Treesitter", icon = { icon = "󰉁", color = "yellow" }, mode = { "n", "x", "o" } },
        { "n", desc = "Next Search Centered", icon = { icon = "󰍉", color = "azure" } },
        { "s", desc = "Flash Jump", icon = { icon = "󰉁", color = "yellow" }, mode = { "n", "x", "o" } },

        { "<leader>a", desc = "Swap Next Parameter", icon = { icon = "󰓡", color = "cyan" } },
        { "<leader>A", desc = "Swap Previous Parameter", icon = { icon = "󰓢", color = "cyan" } },
        { "<leader>e", desc = "Hover Documentation", icon = { icon = "󰋖", color = "azure" } },
        { "<leader>j", desc = "Move Line Down", icon = { icon = "󰁅", color = "cyan" } },
        { "<leader>k", desc = "Move Line Up", icon = { icon = "󰁝", color = "cyan" } },
        { "<leader>j", desc = "Move Selection Down", icon = { icon = "󰁅", color = "cyan" }, mode = "v" },
        { "<leader>k", desc = "Move Selection Up", icon = { icon = "󰁝", color = "cyan" }, mode = "v" },

        { "<leader>b", group = "Buffers", icon = { icon = "󰓩", color = "blue" } },
        { "<leader>bc", desc = "Close Buffer", icon = { icon = "󰅖", color = "red" } },
        { "<leader>be", desc = "Move Buffer Right", icon = { icon = "󰁔", color = "blue" } },
        { "<leader>bp", desc = "Pin Buffer", icon = { icon = "󰐃", color = "yellow" } },
        { "<leader>bq", desc = "Move Buffer Left", icon = { icon = "󰁍", color = "blue" } },

        { "<leader>c", group = "Code", icon = { icon = "󰅩", color = "purple" } },
        { "<leader>ca", desc = "Code Action", icon = { icon = "󰌵", color = "yellow" }, mode = { "n", "v" } },
        { "<leader>cd", desc = "Line Diagnostics", icon = { icon = "󰒡", color = "orange" } },
        { "<leader>cf", desc = "Format", icon = { icon = "󰉼", color = "blue" }, mode = { "n", "v" } },
        { "<leader>ci", desc = "Toggle Inlay Hints", icon = { icon = "󰌵", color = "yellow" } },
        { "<leader>cL", desc = "Lint", icon = { icon = "󰁨", color = "orange" } },
        { "<leader>cm", desc = "Mason", icon = { icon = "󰏗", color = "green" } },
        { "<leader>cl", desc = "LSP List", icon = { icon = "󰘦", color = "purple" } },
        { "<leader>cs", desc = "Document Symbols", icon = { icon = "󰆼", color = "cyan" } },
        { "<leader>cS", desc = "Workspace Symbols", icon = { icon = "󰆼", color = "cyan" } },

        { "<leader>d", group = "Debug", icon = { icon = "", color = "red" } },
        { "<leader>dB", desc = "Conditional Breakpoint", icon = { icon = "", color = "orange" } },
        { "<leader>db", desc = "Toggle Breakpoint", icon = { icon = "", color = "red" } },
        { "<leader>dl", desc = "Run Last Debug", icon = { icon = "󰜉", color = "green" } },
        { "<leader>dr", desc = "Debug REPL", icon = { icon = "", color = "green" } },
        { "<leader>du", desc = "Toggle Debug UI", icon = { icon = "󰙵", color = "blue" } },

        { "<leader>f", group = "Find", icon = { icon = "󰍉", color = "azure" } },
        { "<leader>fb", desc = "Find Buffers", icon = { icon = "󰈚", color = "blue" } },
        { "<leader>fB", desc = "Fast Buffers (Fzf)", icon = { icon = "󰈚", color = "blue" } },
        { "<leader>fe", desc = "File Browser", icon = { icon = "󰉋", color = "yellow" } },
        { "<leader>ff", desc = "Find Files", icon = { icon = "󰈞", color = "azure" } },
        { "<leader>fF", desc = "Fast Files (Fzf)", icon = { icon = "󰈞", color = "azure" } },
        { "<leader>fg", desc = "Live Grep", icon = { icon = "󰱼", color = "green" } },
        { "<leader>fG", desc = "Fast Grep (Fzf)", icon = { icon = "󰱼", color = "green" } },
        { "<leader>fh", desc = "Help Tags", icon = { icon = "󰋖", color = "purple" } },

        { "<leader>g", group = "Git", icon = { icon = "󰊢", color = "orange" } },
        { "<leader>gD", desc = "Close Diff View", icon = { icon = "󰅖", color = "red" } },
        { "<leader>gc", desc = "Commit", icon = { icon = "󰜘", color = "green" } },
        { "<leader>gd", desc = "Diff View", icon = { icon = "󰦓", color = "orange" } },
        { "<leader>gg", desc = "Lazygit", icon = { icon = "󰊢", color = "orange" } },
        { "<leader>gh", desc = "File History", icon = { icon = "󰋚", color = "yellow" } },
        { "<leader>gl", desc = "Pull", icon = { icon = "󰇚", color = "blue" } },
        { "<leader>gp", desc = "Push", icon = { icon = "󰕒", color = "green" } },
        { "<leader>gs", desc = "Status", icon = { icon = "󰊢", color = "orange" } },

        { "<leader>h", group = "Git Hunks", icon = { icon = "󰊢", color = "orange" } },
        { "<leader>hD", desc = "Diff Last Commit", icon = { icon = "󰦓", color = "orange" } },
        { "<leader>hQ", desc = "All Hunks to Quickfix", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>hR", desc = "Reset Buffer", icon = { icon = "󰜉", color = "red" } },
        { "<leader>hS", desc = "Stage Buffer", icon = { icon = "󰐗", color = "green" } },
        { "<leader>hb", desc = "Blame Line", icon = { icon = "󰊢", color = "yellow" } },
        { "<leader>hd", desc = "Diff Index", icon = { icon = "󰦓", color = "orange" } },
        { "<leader>hi", desc = "Inline Preview Hunk", icon = { icon = "󰈈", color = "cyan" } },
        { "<leader>hp", desc = "Preview Hunk", icon = { icon = "󰈈", color = "cyan" } },
        { "<leader>hq", desc = "Buffer Hunks to Quickfix", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>hr", desc = "Reset Hunk", icon = { icon = "󰜉", color = "red" }, mode = { "n", "v" } },
        { "<leader>hs", desc = "Stage Hunk", icon = { icon = "󰐗", color = "green" }, mode = { "n", "v" } },

        { "<leader>l", group = "Local Tools", icon = { icon = "󰒓", color = "grey" } },
        { "<leader>ld", desc = "Lazydocker", icon = { icon = "󰡨", color = "blue" } },

        { "<leader>n", group = "Tests", icon = { icon = "󰙨", color = "green" } },
        { "<leader>nO", desc = "Output Panel", icon = { icon = "󰦪", color = "green" } },
        { "<leader>nT", desc = "Run Project Tests", icon = { icon = "󰙨", color = "green" } },
        { "<leader>nf", desc = "Run File Tests", icon = { icon = "󰈙", color = "green" } },
        { "<leader>no", desc = "Open Test Output", icon = { icon = "󰦪", color = "green" } },
        { "<leader>ns", desc = "Test Summary", icon = { icon = "󰁨", color = "blue" } },
        { "<leader>nt", desc = "Run Nearest Test", icon = { icon = "󰙨", color = "green" } },
        { "<leader>nw", desc = "Watch Tests", icon = { icon = "󰛐", color = "yellow" } },

        { "<leader>p", group = "Python", icon = { icon = "󰌠", color = "yellow" } },
        { "<leader>pv", desc = "Select Virtualenv", icon = { icon = "󰌠", color = "yellow" } },
        { "<leader>py", desc = "Python REPL", icon = { icon = "󰌠", color = "yellow" } },

        { "<leader>G", group = "Go", icon = { icon = "󰟓", color = "cyan" } },
        { "<leader>GF", desc = "Generate File Tests", icon = { icon = "󰙨", color = "green" } },
        { "<leader>GT", desc = "Remove JSON Tags", icon = { icon = "󰅖", color = "red" } },
        { "<leader>Gc", desc = "Generate Comment", icon = { icon = "󰆈", color = "blue" } },
        { "<leader>Gf", desc = "Generate Function Test", icon = { icon = "󰙨", color = "green" } },
        { "<leader>Gi", desc = "Add If Error", icon = { icon = "󰅚", color = "orange" } },
        { "<leader>Gt", desc = "Add JSON Tags", icon = { icon = "󰓹", color = "yellow" } },

        { "<leader>J", group = "Java", icon = { icon = "󰬷", color = "orange" } },
        { "<leader>JT", desc = "Test File", icon = { icon = "󰙨", color = "green" } },
        { "<leader>Jc", desc = "Extract Constant", icon = { icon = "󰐕", color = "purple" }, mode = { "n", "v" } },
        { "<leader>Jm", desc = "Extract Method", icon = { icon = "󰡱", color = "purple" }, mode = "v" },
        { "<leader>Jo", desc = "Organize Imports", icon = { icon = "󰅩", color = "blue" } },
        { "<leader>Jt", desc = "Test Nearest", icon = { icon = "󰙨", color = "green" } },
        { "<leader>Ju", desc = "Update Project Config", icon = { icon = "󰚰", color = "yellow" } },
        { "<leader>Jv", desc = "Extract Variable", icon = { icon = "󰫧", color = "purple" }, mode = { "n", "v" } },

        { "<leader>T", group = "TypeScript", icon = { icon = "󰛦", color = "blue" } },
        { "<leader>Ta", desc = "Add Missing Imports", icon = { icon = "󰐕", color = "green" } },
        { "<leader>Tf", desc = "Fix All", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>Ti", desc = "Organize Imports", icon = { icon = "󰅩", color = "blue" } },
        { "<leader>Tr", desc = "Rename File", icon = { icon = "󰑕", color = "purple" } },
        { "<leader>Tu", desc = "Remove Unused", icon = { icon = "󰆴", color = "red" } },

        { "<leader>r", group = "Refactor", icon = { icon = "󰑕", color = "purple" } },
        { "<leader>rn", desc = "Rename Symbol", icon = { icon = "󰑕", color = "purple" } },

        { "<leader>s", group = "Start", icon = { icon = "󰀻", color = "cyan" } },
        { "<leader>sd", desc = "Open Dashboard", icon = { icon = "󰕮", color = "cyan" } },

        { "<leader>t", group = "Terminal / Toggles", icon = { icon = "", color = "green" } },
        { "<leader>tb", desc = "Toggle Git Blame", icon = { icon = "󰊢", color = "yellow" } },
        { "<leader>tf", desc = "Floating Terminal", icon = { icon = "", color = "green" } },
        { "<leader>th", desc = "Horizontal Terminal", icon = { icon = "", color = "green" } },
        { "<leader>tl", desc = "Toggle Line Highlight", icon = { icon = "󰘤", color = "yellow" } },
        { "<leader>tn", desc = "Toggle Number Highlight", icon = { icon = "󰎠", color = "yellow" } },
        { "<leader>tv", desc = "Vertical Terminal", icon = { icon = "", color = "green" } },
        { "<leader>tw", desc = "Toggle Word Diff", icon = { icon = "󰦓", color = "orange" } },

        { "<leader>x", group = "Diagnostics / Todos", icon = { icon = "󰒡", color = "yellow" } },
        { "<leader>xL", desc = "Location List", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>xQ", desc = "Quickfix List", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>xF", desc = "Todo/Fix FzfLua", icon = { icon = "󰱼", color = "green" } },
        { "<leader>xR", desc = "Todo/Fix Trouble", icon = { icon = "󰒡", color = "orange" } },
        { "<leader>xT", desc = "Todo Telescope", icon = { icon = "󰚢", color = "blue" } },
        { "<leader>xX", desc = "Buffer Diagnostics", icon = { icon = "󰒡", color = "orange" } },
        { "<leader>xf", desc = "Todo FzfLua", icon = { icon = "󰱼", color = "green" } },
        { "<leader>xl", desc = "Todo Location List", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>xq", desc = "Todo Quickfix", icon = { icon = "󰁨", color = "yellow" } },
        { "<leader>xt", desc = "Todo Trouble", icon = { icon = "󰒡", color = "orange" } },
        { "<leader>xx", desc = "Workspace Diagnostics", icon = { icon = "󰒡", color = "red" } },
        { "g", group = "Go To", icon = { icon = "󰁔", color = "cyan" } },
        { "gd", desc = "Go to Definition", icon = { icon = "󰈮", color = "cyan" } },
        { "gi", desc = "Go to Implementation", icon = { icon = "󰡱", color = "cyan" } },
        { "gr", desc = "References", icon = { icon = "󰈇", color = "cyan" } },
        { "gy", desc = "Type Definition", icon = { icon = "󰜁", color = "cyan" } },
        { "gO", desc = "Document Outline", icon = { icon = "󰆼", color = "blue" } },

        { "a", group = "Around Textobject", icon = { icon = "󰅩", color = "cyan" }, mode = { "x", "o" } },
        { "ac", desc = "Around Class", icon = { icon = "󰠱", color = "cyan" }, mode = { "x", "o" } },
        { "am", desc = "Around Function", icon = { icon = "󰊕", color = "cyan" }, mode = { "x", "o" } },
        { "as", desc = "Around Scope", icon = { icon = "󰅩", color = "cyan" }, mode = { "x", "o" } },
        { "i", group = "Inside Textobject", icon = { icon = "󰅩", color = "cyan" }, mode = { "x", "o" } },
        { "ic", desc = "Inside Class", icon = { icon = "󰠱", color = "cyan" }, mode = { "x", "o" } },
        { "ih", desc = "Inside Git Hunk", icon = { icon = "󰊢", color = "orange" }, mode = { "x", "o" } },
        { "im", desc = "Inside Function", icon = { icon = "󰊕", color = "cyan" }, mode = { "x", "o" } },

        { "[", group = "Previous", icon = { icon = "󰁍", color = "blue" } },
        { "]", group = "Next", icon = { icon = "󰁔", color = "blue" } },
        { "[C", desc = "Previous Conditional", icon = { icon = "󰘦", color = "cyan" }, mode = { "n", "x", "o" } },
        { "[M", desc = "Previous Function End", icon = { icon = "󰊕", color = "cyan" }, mode = { "n", "x", "o" } },
        { "[[", desc = "Previous Class Start", icon = { icon = "󰠱", color = "cyan" }, mode = { "n", "x", "o" } },
        { "[]", desc = "Previous Class End", icon = { icon = "󰠱", color = "cyan" }, mode = { "n", "x", "o" } },
        { "[c", desc = "Previous Git Hunk", icon = { icon = "󰊢", color = "orange" } },
        { "[d", desc = "Previous Diagnostic", icon = { icon = "󰒡", color = "orange" } },
        { "[m", desc = "Previous Function Start", icon = { icon = "󰊕", color = "cyan" }, mode = { "n", "x", "o" } },
        { "]d", desc = "Next Diagnostic", icon = { icon = "󰒡", color = "orange" } },
        { "]C", desc = "Next Conditional", icon = { icon = "󰘦", color = "cyan" }, mode = { "n", "x", "o" } },
        { "]M", desc = "Next Function End", icon = { icon = "󰊕", color = "cyan" }, mode = { "n", "x", "o" } },
        { "][", desc = "Next Class End", icon = { icon = "󰠱", color = "cyan" }, mode = { "n", "x", "o" } },
        { "]]", desc = "Next Class Start", icon = { icon = "󰠱", color = "cyan" }, mode = { "n", "x", "o" } },
        { "]c", desc = "Next Git Hunk", icon = { icon = "󰊢", color = "orange" } },
        { "]m", desc = "Next Function Start", icon = { icon = "󰊕", color = "cyan" }, mode = { "n", "x", "o" } },
        { "]o", desc = "Next Loop", icon = { icon = "󰑖", color = "cyan" }, mode = { "n", "x", "o" } },
        { "]s", desc = "Next Scope", icon = { icon = "󰅩", color = "cyan" }, mode = { "n", "x", "o" } },
        { "[t", desc = "Previous Todo", icon = { icon = "󰚢", color = "yellow" } },
        { "]t", desc = "Next Todo", icon = { icon = "󰚢", color = "yellow" } },
        { "]z", desc = "Next Fold", icon = { icon = "󰘖", color = "cyan" }, mode = { "n", "x", "o" } },

        { "<C-Space>", desc = "Trigger Completion", icon = { icon = "󰧑", color = "purple" }, mode = "i" },
        { "<C-j>", desc = "Next Completion / Snippet", icon = { icon = "󰩫", color = "purple" }, mode = "i" },
        { "<C-k>", desc = "Previous Completion / Snippet", icon = { icon = "󰩫", color = "purple" }, mode = "i" },
        { "<C-l>", desc = "Signature Help", icon = { icon = "󰘦", color = "purple" }, mode = "i" },
        { "<CR>", desc = "Accept Completion", icon = { icon = "󰄬", color = "green" }, mode = "i" },
        { "<Tab>", desc = "Next Completion / Snippet", icon = { icon = "󰧑", color = "green" }, mode = "i" },

        { "<C-\\>", desc = "Toggle Terminal", icon = { icon = "", color = "green" }, mode = { "n", "t" } },
        { "<C-h>", desc = "Terminal Window Left", icon = { icon = "󰁍", color = "blue" }, mode = "t" },
        { "<C-j>", desc = "Terminal Window Down", icon = { icon = "󰁅", color = "blue" }, mode = "t" },
        { "<C-k>", desc = "Terminal Window Up", icon = { icon = "󰁝", color = "blue" }, mode = "t" },
        { "<C-l>", desc = "Terminal Window Right", icon = { icon = "󰁔", color = "blue" }, mode = "t" },
        { "<Esc>", desc = "Terminal Normal Mode", icon = { icon = "󰌑", color = "blue" }, mode = "t" },
        { "jk", desc = "Terminal Normal Mode", icon = { icon = "󰌑", color = "blue" }, mode = "t" },
        { "<space>s", desc = "Send Selection to Terminal", icon = { icon = "", color = "green" }, mode = "v" },
    })
end
